### ISSUE TITLE
Retrieves files from only One Subdirectory in th result

### ISSUE THREAD

**Issue by PortalGuy** [siddmegadeth/Cordova-Media-Scanner#2]
If there are more than one subdirectory , the result  returns the files from only one directory, though the service loops through all the files , result does not reflect that

**Comment by siddmegadeth** [comment]
Please share your email I'd. I will share a working demo with you or drop an email to
siddmegadeth@gmail.com

**Comment by PortalGuy** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Hello,First Thanks a lot for putting a awesome feature on github.
Here is the problem I am facing is . I am getting promise returned as soon as first directory with files are processed. But I can see logs that continue to run after result is returned processing other folders . So did not know now how to get all results. Help would be greatly appreciated.ThanksRamesh


Sent from Yahoo Mail for iPhone


On Sunday, January 21, 2018, 3:33 AM, Siddharth <notifications@github.com> wrote:


Please share your email I'd. I will share a working demo with you or drop an email to
siddmegadeth@gmail.com
